Dot digraph colours
gap-packages/Digraphs pull request #330
Opened 2020-07-13 17:59 UTC by marinaanagno

Added coloured options for vertices and edges in DotDigraph and DotSymmetricDigraph. We also used a global variable so that DotDigraph, DotVertexLabelledDigraph, DotColoredDigraph, DotSymmetricDigraph and DotSymmetricColoredDigraph do not have repeated code.

2020-07-15 10:27 UTC, james-d-mitchell commented on doc/z-chap9.xml
> +    <#Include Label="DotColoredDigraph">
This line isn't necessary, and is probably what is causing the CI to fail, I suggest removing it.

2020-07-15 10:27 UTC, james-d-mitchell commented on doc/z-chap9.xml
> +    <#Include Label="DotSymmetricColoredDigraph">
Same for this one.

2020-07-15 10:28 UTC, james-d-mitchell commented on doc/display.xml
> +<#GAPDoc Label="DIGRAPHS_DotDigraph">
We don't usually document functions starting `DIGRAPHS_` these are treated as (kind of) private internal functions/methods.

2020-07-15 10:28 UTC, james-d-mitchell commented on doc/attr.xml
> +<#GAPDoc Label="DigraphNrLoops">
This chunk shouldn't be here, looks like you've branched `DotDigraphColours` off `DigraphNrLoops` but you should have done it from the `master` branch.

2020-07-15 10:29 UTC, james-d-mitchell commented
Thanks for the PR @marinaanagno ! Obviously the CI is failing, I think you need to make a few changes, as mentioned in the comments before having another review.

2020-08-14 08:23 UTC, james-d-mitchell commented on doc/display.xml
> +      only in
Please remove the line break here.

2020-08-14 08:25 UTC, james-d-mitchell commented on doc/display.xml
> +      edges of the graph when displayed.  <P/>
I think you should add more details about what values the arguments can have. I.e. what are the possible "colors" of the vertices and edges? what if I want to specify vertex colors but not edge colors, or vice versa? the list of edge colors has to have the same "shape" as the list of `Outneighbours` right?

2020-08-14 08:26 UTC, james-d-mitchell commented on gap/display.gi
> +  # return DIGRAPHS_DotDigraph(D,
Add a comment that the method above can be replaced with the commented out one when/if Digraphs requires GAP version ??.

2020-08-14 08:26 UTC, james-d-mitchell commented on gap/display.gi
> +                                String(DigraphVertexLabel(D, i)), "\"]")], []);
Same as above, please add a comment.

2020-08-14 08:27 UTC, james-d-mitchell commented on gap/display.gi
> +  return DIGRAPHS_DotSymmetricDigraph(D,
What happens if the list of colors (edge or vertex) is not valid? I.e. if the list is too short? Or has holes?

2020-08-14 08:28 UTC, james-d-mitchell commented on gap/display.gi
> +  # return DIGRAPHS_DotSymmetricDigraph(D,
Add a comment as above.

2020-08-18 16:36 UTC, marinaanagno commented
We made the suggested changes and also we created some new functions `DotVertexColoredDigraph` `DotEdgeColoredDigraph`, `DotSymmetricVertexColoredDigraph` and `DotSymmetricEdgeColoredDigraph` that colour edges and vertices independently.

2020-08-19 13:32 UTC, james-d-mitchell commented
@marinaanagno I'm not sure that you've pushed your changes, can you please double check? If you've addressed my comments, then they should be showing as "outdated", and at present they aren't.

2020-08-19 14:37 UTC, james-d-mitchell requested changes
We discussed this just now, and the only outstanding thing to do is to check that the "color" arguments to these functions are valid.

2020-09-17 07:18 UTC, james-d-mitchell approved these changes

2020-09-17 07:19 UTC, merged